<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Testriq-20s-MacBook-Pro.local" failures="0" tests="4" name="project_ecubix.Test_CheckBusinessGeoCreation" time="32.063" errors="1" timestamp="2025-05-04T12:05:33 IST" skipped="0">
  <testcase classname="project_ecubix.Test_CheckBusinessGeoCreation" name="Test_CheckBusinessGeoCreation_Country" time="5.217">
    <error message="Cannot invoke &quot;java.io.File.getAbsolutePath()&quot; because &quot;latestFile&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because "latestFile" is null
at project_ecubix.Test_CheckBusinessGeoCreation.Test_CheckBusinessGeoCreation_Country(Test_CheckBusinessGeoCreation.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1269)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Test_CheckBusinessGeoCreation_Country -->
  <testcase classname="project_ecubix.Test_CheckBusinessGeoCreation" name="Test_CheckBusinessGeoCreation_ASM" time="10.490"/>
  <testcase classname="project_ecubix.Test_CheckBusinessGeoCreation" name="Test_CheckBusinessGeoCreation_TSM" time="8.334"/>
  <testcase classname="project_ecubix.Test_CheckBusinessGeoCreation" name="Test_CheckBusinessGeoCreation_FDO" time="8.022"/>
</testsuite> <!-- project_ecubix.Test_CheckBusinessGeoCreation -->
